### ISSUE TITLE
project request authentication

### ISSUE THREAD

**Issue by MokiMeow** [Neosoulink/nathan-mande.dev#7]
when I try to load project I get Error fetching repository files: Not Found
Error fetching repository files: Requires authentication

I did have my environment ready it has the GitHub token  yet still i have that problem, I am new to three js thought to work with your site guidance would be helpful thank you

**Comment by Neosoulink** [comment]
Yep, you have to make sure to have the correct env variables.

I'll update the doc soon.
But here's the needed env variables:

```shell
# .env

MODE="development" # or "productucion"

# You can replace those with your socials
GITHUB_LINK="https://github.com/Neosoulink"
LINKEDIN_LINK="https://www.linkedin.com/in/nathan-mande-87b0b2196/"
DISCORD_LINK="https://discord.com/users/552696952882724885"
STACKOVERFLOW_LINK="https://stackoverflow.com/users/11686855/neosoulink"
TWITTER_LINK="https://twitter.com/nsl_nathan"
TELEGRAM_LINK="https://t.me/neosoulink"

GITHUB_TOKEN="string"
GITHUB_USERNAME="Neosoulink"
GITHUB_REPO_NAME="my-resources"
```
> The `.env` should be at the root of the project

**Comment by Neosoulink** [comment]
I'm going to close this issue, let me know if all good on your side

**Comment by MokiMeow** [comment]
> I'm going to close this issue, let me know if all good on your side
Yup that's pretty much it thankyou for the help 😊
